package dev.dioxus.main

import android.content.Intent
import android.os.Bundle
// Replace 'wiki.footnote.app' with your actual package name from Dioxus.toml if different
import wiki.footnote.app.BuildConfig
import dev.dioxus.main.WryActivity

typealias BuildConfig = BuildConfig

class MainActivity : WryActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Check intent on cold start
        intent?.let { handleIntent(it) }
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        // This is the magic line that lets Rust's getIntent() work later
        setIntent(intent)
        handleIntent(intent)
    }

    private fun handleIntent(intent: Intent) {
        intent.data?.let { uri ->
            notifyOnNewIntent(uri.toString())
        }
    }

    // This block tells Android to load your Rust code
    companion object {
        init {
            // "dioxusmain" is the default lib name generated by 'dx'
            System.loadLibrary("dioxusmain")
        }
    }

    private external fun notifyOnNewIntent(uri: String)
}
